#!/bin/sh
# Display the SHA1 of the commit in which configure.ac was last modified.
# If it's not checked in yet, use the SHA1 of HEAD plus -dirty.

if [ ! -d .git ] ; then
    # if no .git directory, assume they're not using Git
    cat "$(dirname $0)/../.tarball-version"
elif git diff --quiet HEAD -- configure.ac ; then
    # configure.ac is not modified
    printf '%s-git' `git describe --always HEAD`
else # configure.ac is modified
    printf '%s-dirty' `git describe --always HEAD`
fi

exit 0
